# Generated by Django 5.0.7 on 2024-08-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('header', models.CharField(max_length=255)),
                ('description1', models.TextField(blank=True)),
                ('description2', models.TextField(blank=True)),
                ('image_src', models.ImageField(upload_to='highlights/')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_src', models.ImageField(upload_to='menu_items/')),
                ('description', models.TextField()),
                ('classification', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='highlight',
            constraint=models.UniqueConstraint(fields=('title', 'header', 'tag'), name='unique_highlight'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_menuitem'),
        ),
    ]
