# Generated by Django 5.0.7 on 2024-08-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_src', models.TextField()),
                ('description', models.TextField()),
                ('classification', models.CharField(max_length=100)),
            ],
        ),
    ]
