# Generated by Django 5.0.7 on 2024-08-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_line', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('background_image', models.ImageField(upload_to='highlights/')),
            ],
        ),
    ]
