# Generated by Django 5.0.7 on 2024-08-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image_src',
            field=models.ImageField(upload_to='menu_items/'),
        ),
        migrations.AddConstraint(
            model_name='highlight',
            constraint=models.UniqueConstraint(fields=('header_line',), name='unique_highlight'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_menuitem'),
        ),
    ]
