# Generated by Django 5.0.7 on 2024-08-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_highlight_unique_highlight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageconfig',
            name='css_variables',
            field=models.JSONField(default=dict),
        ),
    ]
