# Generated by Django 5.0.7 on 2024-09-01 16:25

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_menuitem_allergens_menuitem_calories_menuitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='image_src',
            field=models.ImageField(upload_to=api.models.Highlight.upload_photo_to),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image_src',
            field=models.ImageField(upload_to=api.models.MenuItem.upload_photo_to),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('opening_hours', models.CharField(max_length=255)),
                ('image_src', models.ImageField(upload_to=api.models.Location.upload_photo_to)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.restaurant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('name', 'restaurant'), name='unique_locations'),
        ),
    ]
