# Generated by Django 5.0.7 on 2024-09-09 21:06

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_restaurant_logo_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('classification', models.CharField(max_length=50)),
                ('is_in_stock', models.BooleanField(default=True)),
                ('image_src', models.ImageField(blank=True, upload_to=api.models.ItemOption.upload_photo_to)),
                ('option_for_items', models.ManyToManyField(related_name='option', to='api.menuitem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemoptions', to='api.restaurant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='itemoption',
            constraint=models.UniqueConstraint(fields=('name', 'restaurant'), name='unique_itemoption'),
        ),
    ]
