# Generated by Django 5.0.7 on 2024-09-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_order_selected_items_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='store_location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
