# Generated by Django 5.0.7 on 2024-09-21 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('low_quantity_threshold', models.PositiveIntegerField(default=0)),
                ('item_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='api.itemoption')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='api.location')),
            ],
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('item_option', 'location'), name='unique_itemoption_location'),
        ),
    ]
