from django.core.management.base import BaseCommand
from api.models import ItemOption, Restaurant, MenuItem

class Command(BaseCommand):
    help = 'Populate the Ingredient model with hardcoded data'

    def handle(self, *args, **kwargs):
        restaurant = Restaurant.objects.first()
        if not restaurant:
            self.stdout.write(self.style.ERROR("No restaurant found. Please add a restaurant first."))
            return
        
        ingredients = [
            # Bases
            {
                'name': 'Chopped Romaine',
                'image_src': '/container-91@2x.png',
                'calories': 15,
                'cost': 1.50,
                'classification': 'Base',
                'is_in_stock': True,
                'menu_items': ['Kale Caesar', 'Guacamole Greens', 'Hummus Crunch', 'Buffalo Chicken', 'BBQ Chicken Salad', 'Ranchy Chicken + Rice'],
            },
            {
                'name': 'Spring Mix',
                'image_src': '/container1@2x.png',
                'calories': 10,
                'cost': 1.50,
                'classification': 'Base',
                'is_in_stock': True,
                'menu_items': ['Guacamole Greens', 'Garden Cobb'],
            },
            {
                'name': 'Shredded Kale',
                'image_src': '/container-131@2x.png',
                'calories': 35,
                'cost': 1.50,
                'classification': 'Base',
                'is_in_stock': True,
                'menu_items': ['Kale Caesar', 'Hummus Crunch', 'Buffalo Chicken', 'Super Green Goddess', 'BBQ Chicken Salad', 'Harvest Bowl', 'Shroomami'],
            },
            {
                'name': 'Baby Spinach',
                'image_src': '/container-111@2x.png',
                'calories': 23,
                'cost': 1.75,
                'classification': 'Base',
                'is_in_stock': True,
                'menu_items': ['Super Green Goddess', 'Chicken Pesto Parm'],
            },
            {
                'name': 'Wild Rice',
                'image_src': '/container-141@2x.png',
                'calories': 180,
                'cost': 2.00,
                'classification': 'Base',
                'is_in_stock': True,
                'menu_items': ['Caramelized Garlic Steak', 'Harvest Bowl', 'Shroomami', 'Crispy Rice Bowl'],
            },
            {
                'name': 'Herbed Quinoa',
                'image_src': '/container-141@2x.png',
                'calories': 120,
                'cost': 2.00,
                'classification': 'Base',
                'is_in_stock': True,
                'menu_items': ['Steakhouse Chopped', 'Chicken Pesto Parm', 'Hot Honey Chicken', 'Fish Taco'],
            },
            {
                'name': 'White Rice',
                'image_src': '/container-141@2x.png',
                'calories': 200,
                'cost': 1.75,
                'classification': 'Base',
                'is_in_stock': True,
                'menu_items': ['Miso Glazed Salmon', 'Chicken Avocado Ranch', 'Ranchy Chicken + Rice'],
            },

            # Topping
            {
                'name': 'Crispy Onions',
                'image_src': '/container-151@2x.png',
                'calories': 40,
                'cost': 0.50,
                'classification': 'Topping',
                'is_in_stock': True,
                'menu_items': ['Steakhouse Chopped', 'Miso Glazed Salmon', 'Hot Honey Chicken'],
            },
            {
                'name': 'Pickled Onions',
                'image_src': '/container-171@2x.png',
                'calories': 10,
                'cost': 0.75,
                'classification': 'Topping',
                'is_in_stock': True,
                'menu_items': ['Guacamole Greens', 'Hummus Crunch', 'Buffalo Chicken', 'BBQ Chicken Salad', 'Miso Glazed Salmon'],
            },
            {
                'name': 'Basil',
                'image_src': '/container-191@2x.png',
                'calories': 5,
                'cost': 0.75,
                'classification': 'Topping',
                'is_in_stock': True,
                'menu_items': ['Hummus Crunch', 'Shroomami'],
            },
            {
                'name': 'Raw Carrots',
                'image_src': '/container-201@2x.png',
                'calories': 25,
                'cost': 0.50,
                'classification': 'Topping',
                'is_in_stock': True,
                'menu_items': ['Buffalo Chicken', 'Super Green Goddess', 'Crispy Rice Bowl'],
            },
            {
                'name': 'Chickpeas',
                'image_src': '/container-211@2x.png',
                'calories': 150,
                'cost': 1.00,
                'classification': 'Topping',
                'is_in_stock': True,
                'menu_items': ['Hummus Crunch', 'Super Green Goddess'],
            },
            {
                'name': 'Cilantro',
                'image_src': '/container-221@2x.png',
                'calories': 5,
                'cost': 0.50,
                'classification': 'Topping',
                'is_in_stock': True,
                'menu_items': ['Buffalo Chicken', 'Crispy Rice Bowl', 'Fish Taco'],
            },
            {
                'name': 'Cucumbers',
                'image_src': '/container-231@2x.png',
                'calories': 8,
                'cost': 0.75,
                'classification': 'Topping',
                'is_in_stock': True,
                'menu_items': ['Hummus Crunch', 'Shroomami', 'Miso Glazed Salmon', 'Fish Taco'],
            },
            {
                'name': 'Roasted Sweet Potatoes',
                'image_src': '/container-241@2x.png',
                'calories': 100,
                'cost': 2.00,
                'classification': 'Topping',
                'is_in_stock': True,
                'menu_items': ['Super Green Goddess', 'Garden Cobb', 'Caramelized Garlic Steak', 'Harvest Bowl', 'BBQ Chicken Salad'],
            },
            {
                'name': 'Shredded Cabbage',
                'image_src': '/container-251@2x.png',
                'calories': 15,
                'cost': 0.50,
                'classification': 'Topping',
                'is_in_stock': True,
                'menu_items': ['Guacamole Greens', 'Hummus Crunch', 'Super Green Goddess', 'BBQ Chicken Salad', 'Shroomami', 'Crispy Rice Bowl'],
            },
            {
                'name': 'Spicy Broccoli',
                'image_src': '/container-261@2x.png',
                'calories': 40,
                'cost': 1.50,
                'classification': 'Topping',
                'is_in_stock': True,
                'menu_items': ['Super Green Goddess', 'Caramelized Garlic Steak', 'Chicken Pesto Parm'],
            },
            {
                'name': 'Tomatoes',
                'image_src': '/container-271@2x.png',
                'calories': 20,
                'cost': 0.50,
                'classification': 'Topping',
                'is_in_stock': True,
                'menu_items': ['Kale Caesar', 'Guacamole Greens', 'Hummus Crunch', 'Buffalo Chicken', 'Super Green Goddess', 'Steakhouse Chopped', 'Caramelized Garlic Steak'],
            },
            {
                'name': 'Crispy Rice',
                'image_src': '/container-281@2x.png',
                'calories': 70,
                'cost': 1.00,
                'classification': 'Topping',
                'is_in_stock': True,
                'menu_items': ['Crispy Rice Bowl'],
            },
            {
                'name': 'Roasted Almonds',
                'image_src': '/container-291@2x.png',
                'calories': 120,
                'cost': 2.00,
                'classification': 'Topping',
                'is_in_stock': True,
                'menu_items': ['Super Green Goddess', 'Garden Cobb', 'Harvest Bowl', 'Shroomami', 'Crispy Rice Bowl'],
            },
            {
                'name': 'Tortilla Chips',
                'image_src': '/container-301@2x.png',
                'calories': 150,
                'cost': 1.00,
                'classification': 'Topping',
                'is_in_stock': True,
                'menu_items': ['Guacamole Greens', 'BBQ Chicken Salad', 'Chicken Avocado Ranch', 'Fish Taco'],
            },

            # More Premiums
            {
                'name': 'Caramelized Garlic Steak',
                'image_src': '/container-311@2x.png',
                'calories': 320,
                'cost': 6.00,
                'classification': 'Premium',
                'is_in_stock': True,
                'menu_items': ['Caramelized Garlic Steak', 'Steakhouse Chopped', 'Kale Caesar (Steak)'],
            },
            {
                'name': 'Goat Cheese',
                'image_src': '/container-321@2x.png',
                'calories': 90,
                'cost': 2.00,
                'classification': 'Premium',
                'is_in_stock': True,
                'menu_items': ['Hummus Crunch', 'Harvest Bowl'],
            },
            {
                'name': 'Avocado',
                'image_src': '/container-331@2x.png',
                'calories': 160,
                'cost': 2.00,
                'classification': 'Premium',
                'is_in_stock': True,
                'menu_items': ['Guacamole Greens', 'Garden Cobb', 'Miso Glazed Salmon', 'Chicken Avocado Ranch', 'Fish Taco'],
            },
            {
                'name': 'Veg Slaw',
                'image_src': '/container-341@2x.png',
                'calories': 50,
                'cost': 1.00,
                'classification': 'Premium',
                'is_in_stock': True,
                'menu_items': ['Hot Honey Chicken'],
            },
            {
                'name': 'Shaved Parmesan',
                'image_src': '/container-351@2x.png',
                'calories': 90,
                'cost': 1.50,
                'classification': 'Premium',
                'is_in_stock': True,
                'menu_items': ['Kale Caesar', 'Garden Cobb', 'Steakhouse Chopped', 'Chicken Pesto Parm'],
            },
            {
                'name': 'Roasted Tofu',
                'image_src': '/container-361@2x.png',
                'calories': 140,
                'cost': 2.00,
                'classification': 'Premium',
                'is_in_stock': True,
                'menu_items': ['Shroomami'],
            },
            {
                'name': 'Miso Glazed Salmon',
                'image_src': '/container-371@2x.png',
                'calories': 280,
                'cost': 6.50,
                'classification': 'Premium',
                'is_in_stock': True,
                'menu_items': ['Miso Glazed Salmon', 'Fish Taco'],
            },
            {
                'name': 'Parmesan Crisps',
                'image_src': '/container-381@2x.png',
                'calories': 100,
                'cost': 1.50,
                'classification': 'Premium',
                'is_in_stock': True,
                'menu_items': ['Kale Caesar', 'Ranchy Chicken + Rice'],
            },
            {
                'name': 'Warm Portobello Mix',
                'image_src': '/container-391@2x.png',
                'calories': 70,
                'cost': 2.00,
                'classification': 'Premium',
                'is_in_stock': True,
                'menu_items': ['Shroomami'],
            },
            {
                'name': 'Hummus',
                'image_src': '/container-401@2x.png',
                'calories': 80,
                'cost': 1.50,
                'classification': 'Premium',
                'is_in_stock': True,
                'menu_items': ['Hummus Crunch'],
            },
            {
                'name': 'Hard Boiled Egg',
                'image_src': '/container-441@2x.png',
                'calories': 70,
                'cost': 1.00,
                'classification': 'Premium',
                'is_in_stock': True,
                'menu_items': ['Garden Cobb'],
            },

            # Dressings
            {
                'name': 'Red Wine Vinaigrette',
                'image_src': '/container-46@2x.png',
                'calories': 90,
                'cost': 1.00,
                'classification': 'Dressing',
                'is_in_stock': True,
                'menu_items': [],
            },
            {
                'name': 'Caesar',
                'image_src': '/container-47@2x.png',
                'calories': 100,
                'cost': 1.00,
                'classification': 'Dressing',
                'is_in_stock': True,
                'menu_items': ['Kale Caesar', 'Buffalo Chicken', 'Steakhouse Chopped'],
            },
            {
                'name': 'Spicy Cashew',
                'image_src': '/container-48@2x.png',
                'calories': 80,
                'cost': 1.00,
                'classification': 'Dressing',
                'is_in_stock': True,
                'menu_items': ['Miso Glazed Salmon', 'Crispy Rice Bowl'],
            },
            {
                'name': 'Lemon Squeeze',
                'image_src': '/container-49@2x.png',
                'calories': 5,
                'cost': 0.25,
                'classification': 'Dressing',
                'is_in_stock': True,
                'menu_items': ['Kale Caesar', 'Guacamole Greens'],
            },
            {
                'name': 'Honey BBQ Sauce',
                'image_src': '/container-50@2x.png',
                'calories': 60,
                'cost': 1.00,
                'classification': 'Dressing',
                'is_in_stock': True,
                'menu_items': ['BBQ Chicken Salad'],
            },
            {
                'name': 'Extra Virgin Olive Oil',
                'image_src': '/container-511@2x.png',
                'calories': 120,
                'cost': 1.00,
                'classification': 'Dressing',
                'is_in_stock': True,
                'menu_items': [],
            },
            {
                'name': 'Green Goddess Ranch',
                'image_src': '/container-54@2x.png',
                'calories': 120,
                'cost': 1.00,
                'classification': 'Dressing',
                'is_in_stock': True,
                'menu_items': ['Super Green Goddess', 'Steakhouse Chopped', 'Chicken Pesto Parm', 'Chicken Avocado Ranch'],
            },
            {
                'name': 'Lime Cilantro Jalapeno Vinaigrette',
                'image_src': '/container-55@2x.png',
                'calories': 80,
                'cost': 1.00,
                'classification': 'Dressing',
                'is_in_stock': True,
                'menu_items': ['Guacamole Greens', 'Fish Taco'],
            },
            {
                'name': 'Hot Honey Mustard Sauce',
                'image_src': '/container-56@2x.png',
                'calories': 60,
                'cost': 1.00,
                'classification': 'Dressing',
                'is_in_stock': True,
                'menu_items': ['Hot Honey Chicken'],
            },
            {
                'name': 'Pesto Vinaigrette',
                'image_src': '/container-611@2x.png',
                'calories': 100,
                'cost': 1.00,
                'classification': 'Dressing',
                'is_in_stock': True,
                'menu_items': ['Caramelized Garlic Steak', 'Chicken Pesto Parm', 'Harvest Bowl', 'Hummus Crunch'],
            },
            {
                'name': 'Miso Sesame Ginger',
                'image_src': '/container-58@2x.png',
                'calories': 80,
                'cost': 1.00,
                'classification': 'Dressing',
                'is_in_stock': True,
                'menu_items': ['Shroomami'],
            },
            {
                'name': 'Balsamic Vinegar',
                'image_src': '/container-60@2x.png',
                'calories': 60,
                'cost': 1.00,
                'classification': 'Dressing',
                'is_in_stock': True,
                'menu_items': ['Garden Cobb', 'Harvest Bowl'],
            },
        ]


        menu_items = {menu_item.name : menu_item for menu_item in MenuItem.objects.all()}
        for ingredient_data in ingredients:
            menu_items_for_ingredient = ingredient_data.pop('menu_items', [])
            ingredient, created = ItemOption.objects.get_or_create(restaurant=restaurant, **ingredient_data)
            if created:
                self.stdout.write(self.style.SUCCESS(f"Added {ingredient.name}"))
            else:
                self.stdout.write(self.style.WARNING(f"{ingredient.name} already exists"))

            # Associate the Ingredient with the related MenuItems
            for menu_item_name in menu_items_for_ingredient:
                if menu_item_name in menu_items:
                    ingredient.option_for_items.add(menu_items[menu_item_name])
                    self.stdout.write(self.style.SUCCESS(f"Linked {ingredient.name} to {menu_item_name}"))
                else:
                    self.stdout.write(self.style.ERROR(f"MenuItem {menu_item_name} not found for ingredient {ingredient.name}"))